kind: ConfigMap
apiVersion: v1
metadata:
  name: example-pod-config.yml
  namespace: myproject
data:
  hawkular-openshift-agent: |
    endpoints:
    - type: jolokia
      collection_interval: 15s
      protocol: "https"
      tls:
        skip_certificate_validation: true
      port: 8778
      credentials:
        username: jolokia
        password: eOdlZ2IM2SIm9ZgVaRfZM5OEcQGkm4 
      path: /jolokia/
      tags:
        name: ${POD:label[project]}
      metrics:
      # Camel Context Metrics
      - name: org.apache.camel:name=*,context=*,type=context#ExchangesCompleted
        type: counter
        id: bean.{context}.{name}.ExchangesCompleted
      - name: org.apache.camel:name=*,context=*,type=context#ExchangesFailed
        type: counter
        id: bean.{context}.{name}.ExchangesFailed
      - name: org.apache.camel:name=*,context=*,type=context#ExchangesTotal
        type: counter
        id: bean.{context}.{name}.ExchangesTotal
      - name: org.apache.camel:name=*,context=*,type=context#MinProcessingTime
        type: counter
        id: bean.{context}.{name}.MinimumProcessingTime
      - name: org.apache.camel:name=*,context=*,type=context#MeanProcessingTime
        type: gauge
        id: bean.{context}.{name}.MeanProcessingTime
      - name: org.apache.camel:name=*,context=*,type=context#MaxProcessingTime
        type: gauge
        id: bean.{context}.{name}.MaxProcessingTime
      - name: org.apache.camel:name=*,context=*,type=context#TotalProcessingTime
        type: gauge
        id: bean.{context}.{name}.TotalProcessingTime
      - name: org.apache.camel:name=*,context=*,type=context#LastProcessingTime
        type: gauge
        id: bean.{context}.{name}.LastProcessingTime
      # Camel Processor Metrics
      - name: org.apache.camel:name=*,context=*,type=processors#ExchangesCompleted
        type: counter
        id: bean.{context}.processor.{name}.ExchangesCompleted
      - name: org.apache.camel:name=*,context=*,type=processors#ExchangesFailed
        type: counter
        id: bean.{context}.processor.{name}.ExchangesFailed
      - name: org.apache.camel:name=*,context=*,type=processors#ExchangesTotal
        type: counter
        id: bean.{context}.processor.{name}.ExchangesTotal
      - name: org.apache.camel:name=*,context=*,type=processors#MinProcessingTime
        type: counter
        id: bean.{context}.processor.{name}.MinimumProcessingTime
      - name: org.apache.camel:name=*,context=*,type=processors#MeanProcessingTime
        type: gauge
        id: bean.{context}.processor.{name}.MeanProcessingTime
      - name: org.apache.camel:name=*,context=*,type=processors#MaxProcessingTime
        type: gauge
        id: bean.{context}.processor.{name}.MaxProcessingTime
      - name: org.apache.camel:name=*,context=*,type=processors#TotalProcessingTime
        type: gauge
        id: bean.{context}.processor.{name}.TotalProcessingTime
      - name: org.apache.camel:name=*,context=*,type=processors#LastProcessingTime
        type: gauge
        id: bean.{context}.processor.{name}.LastProcessingTime
      # Camel Route Metrics
      - name: org.apache.camel:type=routes,name=*,context=*
        type: gauge
        id: bean.{context}.routes.{name}.InflightExchanges
      